export const MOCK_BATCHES = [
  {
    id: 1,
    name: "Follow-up #2",
    address: "35 Jones St",
    suburb: "Balmain",
    bot: "Lead Qual 2",
    list: "Warm Leads",
    time: "11:00am, 14-Mar-25",
    callsTotal: 150,
    remaining: 20,
    status: "Completed",
    pct: "100%",
    batchSummary: "Lead Qual #2",
    property: "35 Jones St",
    startDateTime: "11:00am, 14-Mar-25",
    remainingCalls: 20,
    pctCompleted: "100%",
    voicemailRate: "10%",
    dropoutRate: "5%",
    hangupRate: "5%",
    totalTime: "320m 22s",
    averageTime: "2m 30s",
    aiInsights: {
      qualifiedBuyers: 15,
      attendingEvent: 30,
      topBuyers: 5,
      summary: [
        "There were 15 qualified buyers out of 150 leads",
        "Common feedback was the kitchen was too small",
        "Tom Cruise wants to make an offer",
      ],
    },
    calls: [
      {
        contact: "Tom Cruise",
        time: "11:00am, 14-Mar-25",
        duration: "1m 20s",
        result: "Pick Up",
        status: "Completed",
      },
      {
        contact: "Nicole Kidman",
        time: "12:30pm, 14-Mar-25",
        duration: "2m 15s",
        result: "Voicemail",
        status: "Completed",
      },
      {
        contact: "Hugh Jackman",
        time: "2:00pm, 14-Mar-25",
        duration: "3m 30s",
        result: "Drop Out",
        status: "Completed",
      },
    ],
  },
  {
    id: 2,
    name: "Follow-up #3",
    address: "10 Bird St",
    suburb: "Five Dock",
    bot: "Initial Contact",
    list: "Cold Leads",
    time: "12:30pm, 14-Mar-25",
    callsTotal: 150,
    remaining: 30,
    status: "IN progress",
    pct: "60%",
    batchSummary: "Follow-up #3",
    property: "10 Bird St",
    startDateTime: "12:30pm, 14-Mar-25",
    remainingCalls: 30,
    pctCompleted: "60%",
    voicemailRate: "15%",
    dropoutRate: "8%",
    hangupRate: "3%",
    totalTime: "180m 10s",
    averageTime: "2m 00s",
    aiInsights: {
      qualifiedBuyers: 8,
      attendingEvent: 20,
      topBuyers: 3,
      summary: [
        "8 qualified buyers identified so far",
        "Most leads interested in open-plan living",
        "Nicole Kidman expressed strong interest",
      ],
    },
    calls: [
      {
        contact: "Nicole Kidman",
        time: "12:30pm, 14-Mar-25",
        duration: "2m 15s",
        result: "Pick Up",
        status: "Completed",
      },
      {
        contact: "Hugh Jackman",
        time: "1:00pm, 14-Mar-25",
        duration: "0m 45s",
        result: "Voicemail",
        status: "Completed",
      },
    ],
  },
  {
    id: 3,
    name: "Follow-up #4",
    address: "21 Thompson St",
    suburb: "Drummoyne",
    bot: "Follow up",
    list: "Qualified Leads",
    time: "2:00pm, 14-Mar-25",
    callsTotal: 150,
    remaining: 42,
    status: "IN progress",
    pct: "0%",
    batchSummary: "Follow-up #4",
    property: "21 Thompson St",
    startDateTime: "2:00pm, 14-Mar-25",
    remainingCalls: 42,
    pctCompleted: "0%",
    voicemailRate: "20%",
    dropoutRate: "12%",
    hangupRate: "7%",
    totalTime: "0m 00s",
    averageTime: "0m 00s",
    aiInsights: {
      qualifiedBuyers: 0,
      attendingEvent: 0,
      topBuyers: 0,
      summary: ["Batch has not started yet", "Scheduled for 2:00pm"],
    },
    calls: [],
  },
  {
    id: 4,
    name: "Follow-up #5",
    address: "77 Oak Rd",
    suburb: "Strathfield",
    bot: "Proposal Sent",
    list: "Converted Leads",
    time: "3:30pm, 14-Mar-25",
    callsTotal: 150,
    remaining: 12,
    status: "IN progress",
    pct: "30%",
    batchSummary: "Follow-up #5",
    property: "77 Oak Rd",
    startDateTime: "3:30pm, 14-Mar-25",
    remainingCalls: 12,
    pctCompleted: "30%",
    voicemailRate: "8%",
    dropoutRate: "4%",
    hangupRate: "2%",
    totalTime: "95m 40s",
    averageTime: "2m 10s",
    aiInsights: {
      qualifiedBuyers: 6,
      attendingEvent: 12,
      topBuyers: 2,
      summary: [
        "6 qualified buyers so far",
        "Margot Robbie requested a follow-up call",
      ],
    },
    calls: [
      {
        contact: "Margot Robbie",
        time: "3:30pm, 14-Mar-25",
        duration: "2m 10s",
        result: "Pick Up",
        status: "Completed",
      },
      {
        contact: "Chris Hemsworth",
        time: "4:00pm, 14-Mar-25",
        duration: "1m 05s",
        result: "Hangup",
        status: "Completed",
      },
    ],
  },
  {
    id: 5,
    name: "Follow-up #6",
    address: "5 Pine Ln",
    suburb: "Burwood",
    bot: "Closed - Won",
    list: "Nurtured Leads",
    time: "5:00pm, 14-Mar-25",
    callsTotal: 150,
    remaining: 65,
    status: "Scheduled",
    pct: "90%",
    batchSummary: "Follow-up #6",
    property: "5 Pine Ln",
    startDateTime: "5:00pm, 14-Mar-25",
    remainingCalls: 65,
    pctCompleted: "90%",
    voicemailRate: "5%",
    dropoutRate: "2%",
    hangupRate: "1%",
    totalTime: "280m 00s",
    averageTime: "1m 52s",
    aiInsights: {
      qualifiedBuyers: 20,
      attendingEvent: 45,
      topBuyers: 8,
      summary: [
        "20 qualified buyers identified",
        "Strong interest in the backyard and pool",
        "Chris Hemsworth ready to submit an offer",
      ],
    },
    calls: [
      {
        contact: "Chris Hemsworth",
        time: "5:00pm, 14-Mar-25",
        duration: "1m 52s",
        result: "Pick Up",
        status: "Completed",
      },
      {
        contact: "Tom Cruise",
        time: "5:30pm, 14-Mar-25",
        duration: "2m 00s",
        result: "Pick Up",
        status: "Completed",
      },
    ],
  },
];

// Backwards compat — points to batch 1
export const MOCK_BATCH_DETAIL = MOCK_BATCHES[0];

export const MOCK_CONTACTS = [
  { id: 1, name: "Tom Cruise", phone: "+6123456789" },
  { id: 2, name: "Nicole Kidman", phone: "+6123456790" },
  { id: 3, name: "Hugh Jackman", phone: "+6123456791" },
  { id: 4, name: "Margot Robbie", phone: "+6145678901" },
  { id: 5, name: "Chris Hemsworth", phone: "+6156789012" },
];

export const MOCK_PROPERTIES_LIST = [
  "35 Jones St",
  "10 Bird St",
  "21 Thompson St",
  "77 Oak Rd",
  "5 Pine Ln",
];

export const MOCK_BOTS_LIST = [
  "Lead Qual 2",
  "Initial Contact",
  "Follow up",
  "Proposal Sent",
  "Closed - Won",
];

export const MOCK_CONTACT_LISTS = [
  "Warm Leads",
  "Cold Leads",
  "Qualified Leads",
  "Converted Leads",
  "Nurtured Leads",
];
