export const MOCK_BATCHES = [
  {
    id: 1,
    name: "Follow-up #2",
    address: "35 Jones St",
    suburb: "Balmain",
    bot: "Lead Qual 2",
    list: "Warm Leads",
    time: "11:00am, 14-Mar-25",
    callsTotal: 150,
    remaining: 20,
    status: "Completed",
    pct: "100%",
  },
  {
    id: 2,
    name: "Follow-up #3",
    address: "10 Bird St",
    suburb: "Five Dock",
    bot: "Initial Contact",
    list: "Cold Leads",
    time: "12:30pm, 14-Mar-25",
    callsTotal: 150,
    remaining: 30,
    status: "IN progress",
    pct: "60%",
  },
  {
    id: 3,
    name: "Follow-up #4",
    address: "21 Thompson St",
    suburb: "Drummoyne",
    bot: "Follow up",
    list: "Qualified Leads",
    time: "2:00pm, 14-Mar-25",
    callsTotal: 150,
    remaining: 42,
    status: "IN progress",
    pct: "0%",
  },
  {
    id: 4,
    name: "Follow-up #5",
    address: "77 Oak Rd",
    suburb: "Strathfield",
    bot: "Proposal Sent",
    list: "Converted Leads",
    time: "3:30pm, 14-Mar-25",
    callsTotal: 150,
    remaining: 12,
    status: "IN progress",
    pct: "30%",
  },
  {
    id: 5,
    name: "Follow-up #6",
    address: "5 Pine Ln",
    suburb: "Burwood",
    bot: "Closed - Won",
    list: "Nurtured Leads",
    time: "5:00pm, 14-Mar-25",
    callsTotal: 150,
    remaining: 65,
    status: "Scheduled",
    pct: "90%",
  },
];

export const MOCK_BATCH_DETAIL = {
  id: 1,
  batchSummary: "Lead Qual #2",
  property: "35 Jones St",
  suburb: "Balmain",
  status: "Completed",
  startDateTime: "11:00am, 14-Mar-25",
  callsTotal: 150,
  remainingCalls: 75,
  pctCompleted: "55%",
  voicemailRate: "10%",
  dropoutRate: "5%",
  hangupRate: "5%",
  totalTime: "320m 22s",
  averageTime: "2m 30s",
  aiInsights: {
    qualifiedBuyers: 15,
    attendingEvent: 30,
    topBuyers: 5,
    summary: [
      "there were 15 qualified buyers out of 150 leads",
      "Common feedback was the kitchen was too small",
      "Tom Cruise wants to make an offer",
    ],
  },
  calls: [
    {
      contact: "Tom Cruise",
      time: "11:00am, 14-Mar-25",
      duration: "1m 20s",
      result: "Pick Up",
      status: "Completed",
    },
    {
      contact: "Nicole Kidman",
      time: "12:30pm, 14-Mar-25",
      duration: "2m 15s",
      result: "Voice mail",
      status: "Completed",
    },
    {
      contact: "Hugh Jackman",
      time: "2:00pm, 14-Mar-25",
      duration: "3m 30s",
      result: "Drop Out",
      status: "Completed",
    },
  ],
};

export const MOCK_CONTACTS = [
  { id: 1, name: "Tom Cruise", phone: "+6123456789" },
  { id: 2, name: "Nicole Kidman", phone: "+6123456790" },
  { id: 3, name: "Hugh Jackman", phone: "+6123456791" },
];
export const MOCK_PROPERTIES_LIST = [
  "35 Jones St",
  "10 Bird St",
  "21 Thompson St",
  "77 Oak Rd",
  "5 Pine Ln",
];
export const MOCK_BOTS_LIST = [
  "Lead Qual 2",
  "Initial Contact",
  "Follow up",
  "Proposal Sent",
];
export const MOCK_CONTACT_LISTS = [
  "Warm Leads",
  "Cold Leads",
  "Qualified Leads",
  "Converted Leads",
  "Nurtured Leads",
];
