// ── Status options ────────────────────────────────────────────────────────────
export const CONTACT_STATUS_OPTIONS = [
  "Looking to purchase",
  "Looking to sell",
  "Not looking",
  "Completed",
];

export const INTEREST_OPTIONS = ["Hot", "Warm", "Cold", "Unknown"];

// ── Main contacts list ────────────────────────────────────────────────────────
export const MOCK_CONTACTS = [
  {
    id: 1,
    name: "Tom Cruise",
    phone: "+61123456789",
    email: "John.doe@domain.com",
    properties: "35 Jones St",
    calls: 150,
    lastContacted: "11:00am, 14-Mar-25",
    interested: "35 Jones St",
    address: "35 Jones St",
    status: "Looking to purchase",
    profile: "45 year old single dad with 3 kids",
    aiInsights: [
      "45 year old single dad with 3 kids",
      "looking for a 2 bedroom apartment in North Sydney",
      "Inspected 35 Thompson St on 3-Mar-25, was too expensive",
      "Is planning to attend the inspection of 15 High St on 15-Mar-25",
    ],
    linkedProperties: [
      { address: "35 Jones St", interest: "Hot" },
      { address: "5 Pine Ln", interest: "Cold" },
      { address: "35 Example St", interest: "Warm" },
    ],
    callHistory: [
      {
        batch: "Follow-up #2",
        time: "11:00am, 14-Mar-25",
        duration: "1m 20s",
        address: "21 Thompson St",
        bot: "Lead Qual 2",
        result: "Pick Up",
        status: "Completed",
      },
      {
        batch: "Follow-up #3",
        time: "12:30pm, 14-Mar-25",
        duration: "2m 15s",
        address: "77 Oak Rd",
        bot: "Initial Contact",
        result: "Voice mail",
        status: "IN progress",
      },
      {
        batch: "Follow-up #4",
        time: "2:00pm, 14-Mar-25",
        duration: "3m 30s",
        address: "5 Pine Ln",
        bot: "Follow up",
        result: "Drop Out",
        status: "Completed",
      },
    ],
  },
  {
    id: 2,
    name: "Nicole Kidman",
    phone: "+61234567890",
    email: "nicole.kidman@domain.com",
    properties: "35 Jones St",
    calls: 150,
    lastContacted: "12:30pm, 14-Mar-25",
    interested: "5 Pine Ln",
    address: "35 Jones St",
    status: "Looking to sell",
    profile: "50 year old professional, downsizing after kids moved out",
    aiInsights: [
      "Looking to sell her property in Five Dock",
      "Has been in the market for 3 months",
      "Prefers auction over private sale",
    ],
    linkedProperties: [
      { address: "35 Jones St", interest: "Warm" },
      { address: "5 Pine Ln", interest: "Hot" },
    ],
    callHistory: [
      {
        batch: "Follow-up #2",
        time: "12:30pm, 14-Mar-25",
        duration: "2m 15s",
        address: "35 Jones St",
        bot: "Lead Qual 2",
        result: "Pick Up",
        status: "Completed",
      },
    ],
  },
  {
    id: 3,
    name: "Hugh Jackman",
    phone: "+61345678901",
    email: "hugh.jackman@domain.com",
    properties: "21 Thompson St",
    calls: 150,
    lastContacted: "2:00pm, 14-Mar-25",
    interested: "35 Jones St",
    address: "21 Thompson St",
    status: "Not looking",
    profile: "38 year old investor with a portfolio of 4 properties",
    aiInsights: [
      "Currently not actively looking but open to opportunities",
      "Has budget of $2.5M for the right property",
    ],
    linkedProperties: [{ address: "21 Thompson St", interest: "Cold" }],
    callHistory: [
      {
        batch: "Follow-up #3",
        time: "2:00pm, 14-Mar-25",
        duration: "3m 30s",
        address: "21 Thompson St",
        bot: "Follow up",
        result: "Drop Out",
        status: "Completed",
      },
    ],
  },
  {
    id: 4,
    name: "Margot Robbie",
    phone: "+61456789012",
    email: "margot.robbie@domain.com",
    properties: "77 Oak Rd",
    calls: 150,
    lastContacted: "3:30pm, 14-Mar-25",
    interested: "35 Jones St",
    address: "77 Oak Rd",
    status: "Looking to purchase",
    profile: "29 year old first-home buyer, pre-approved for $1.2M",
    aiInsights: [
      "First home buyer with pre-approval",
      "Looking for 3 bed 2 bath in inner west",
      "Inspected 77 Oak Rd, very interested",
    ],
    linkedProperties: [
      { address: "77 Oak Rd", interest: "Hot" },
      { address: "5 Pine Ln", interest: "Warm" },
    ],
    callHistory: [
      {
        batch: "Follow-up #4",
        time: "3:30pm, 14-Mar-25",
        duration: "4m 05s",
        address: "77 Oak Rd",
        bot: "Proposal Sent",
        result: "Pick Up",
        status: "Completed",
      },
    ],
  },
  {
    id: 5,
    name: "Chris Hemsworth",
    phone: "+61567890123",
    email: "chris.hemsworth@domain.com",
    properties: "5 Pine Ln",
    calls: 150,
    lastContacted: "5:00pm, 14-Mar-25",
    interested: "35 Jones St",
    address: "5 Pine Ln",
    status: "Looking to sell",
    profile: "44 year old upgrading family home",
    aiInsights: [
      "Selling current 3-bed to upgrade to 5-bed",
      "Needs to sell before purchasing",
    ],
    linkedProperties: [{ address: "5 Pine Ln", interest: "Warm" }],
    callHistory: [
      {
        batch: "Follow-up #5",
        time: "5:00pm, 14-Mar-25",
        duration: "5m 45s",
        address: "5 Pine Ln",
        bot: "Closed - Won",
        result: "Pick Up",
        status: "Completed",
      },
    ],
  },
];

export const AVAILABLE_PROPERTIES = [
  {
    id: 1,
    address: "35 Jones St",
    suburb: "Balmain",
    agent: "John Mcmahon",
    batch: 5,
    type: "Sale",
    description: "A 4-bed 5-bath man...",
    listed: "13-Mar-25",
    auction: "13-Apr-25",
    status: "Pre-Launched",
  },
  {
    id: 2,
    address: "10 Bird St",
    suburb: "Five Dock",
    agent: "Barbara Corcoran",
    batch: 6,
    type: "Rental",
    description: "A 3-bed 2-bath apa...",
    listed: "14-Mar-25",
    auction: "14-Apr-25",
    status: "Closed",
  },
  {
    id: 3,
    address: "21 Thompson St",
    suburb: "Drummoyne",
    agent: "Ryan Serhant",
    batch: 7,
    type: "Sale",
    description: "A cozy 2-bed 1-bat...",
    listed: "15-Mar-25",
    auction: "15-Apr-25",
    status: "Live",
  },
  {
    id: 4,
    address: "77 Oak Rd",
    suburb: "Strathfield",
    agent: "Sofia Vergara",
    batch: 8,
    type: "Rental",
    description: "A luxurious pentho...",
    listed: "16-Mar-25",
    auction: "16-Apr-25",
    status: "Live",
  },
  {
    id: 5,
    address: "5 Pine Ln",
    suburb: "Burwood",
    agent: "David Beckham",
    batch: 9,
    type: "Rental",
    description: "A charming studio...",
    listed: "17-Mar-25",
    auction: "17-Apr-25",
    status: "Pre-Launched",
  },
  {
    id: 6,
    address: "14 Cedar Blvd",
    suburb: "Ashfield",
    agent: "Emma Stone",
    batch: 10,
    type: "Sale",
    description: "A spacious 5-bed...",
    listed: "18-Mar-25",
    auction: "18-Apr-25",
    status: "Live",
  },
];
