export const MOCK_CALLS = [
  {
    id: 1,
    contact: "Tom Cruise",
    suburb: "Balmain",
    property: "35 Jones St",
    type: "Inbound",
    batch: "Follow-up #2",
    bot: "Lead Qual 2",
    time: "11:00am, 14-Mar-25",
    duration: "1m 20s",
    successEvaluation: "Warm",
    status: "Completed",
  },
  {
    id: 2,
    contact: "Nicole Kidman",
    suburb: "Five Dock",
    property: "10 Bird St",
    type: "Outbound",
    batch: "Follow-up #3",
    bot: "Initial Contact",
    time: "12:30pm, 14-Mar-25",
    duration: "2m 15s",
    successEvaluation: "Cold",
    status: "Completed",
  },
  {
    id: 3,
    contact: "Hugh Jackman",
    suburb: "Drummoyne",
    property: "21 Thompson St",
    type: "Inbound",
    batch: "Follow-up #4",
    bot: "Follow up",
    time: "2:00pm, 14-Mar-25",
    duration: "3m 30s",
    successEvaluation: "Unknown",
    status: "Completed",
  },
  {
    id: 4,
    contact: "Margot Robbie",
    suburb: "Strathfield",
    property: "77 Oak Rd",
    type: "Outbound",
    batch: "Follow-up #5",
    bot: "Proposal Sent",
    time: "3:30pm, 14-Mar-25",
    duration: "4m 05s",
    successEvaluation: "Hot",
    status: "Completed",
  },
  {
    id: 5,
    contact: "Chris Hemsworth",
    suburb: "Burwood",
    property: "5 Pine Ln",
    type: "Inbound",
    batch: "Follow-up #6",
    bot: "Closed - Won",
    time: "5:00pm, 14-Mar-25",
    duration: "5m 45s",
    successEvaluation: "Hot",
    status: "Completed",
  },
];

export const MOCK_CALL_DETAIL = {
  id: 1,
  contact: "Tom Cruise",
  time: "11:00am, 14-Mar-25",
  address: "35 Jones St",
  suburb: "Balmain",
  type: "Outbound",
  bot: "Lead Qual 2",
  batch: "Follow-up #2",
  duration: "3 m 20 s",
  status: "Completed",
  recordingDuration: "02:12",
  aiInsights: {
    qualifiedBuyers: "Yes",
    attendingEvent: "Yes",
    interestLevel: "Hot",
    summary: [
      "there were 15 qualified buyers out of 150 leads",
      "Common feedback was the kitchen was too small",
      "Tom Cruise wants to make an offer",
    ],
  },
  callSummary:
    "Tom Cruise is not interested in 35 Jones St, it is too expensive",
  transcript: [
    { role: "bot", text: "Hi How are you?" },
    { role: "client", text: "I Am Fine who is this?" },
    {
      role: "bot",
      text: "This is an automated call from VOXworks regarding 35 Jones St.",
    },
    { role: "client", text: "I see, what is this about?" },
  ],
};
